# Generated by Django 6.0.7 on 2026-07-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_hydration'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydration',
            name='drink_type',
            field=models.CharField(choices=[('Water', '💧 Water'), ('Coffee', '☕ Coffee'), ('Tea', '🍵 Tea')], default='Water', max_length=20),
        ),
        migrations.AddField(
            model_name='hydration',
            name='unit',
            field=models.CharField(choices=[('ml', 'ml'), ('cups', 'cups'), ('glasses', 'glasses')], default='ml', max_length=10),
        ),
        migrations.AlterField(
            model_name='hydration',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
