# Generated by Django 6.0.7 on 2026-07-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_hydration_drink_type_hydration_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydration',
            name='unit',
            field=models.CharField(choices=[('ml', 'ml'), ('cups', 'cups')], default='ml', max_length=10),
        ),
    ]
