# Generated by Django 6.0.7 on 2026-07-18 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_slept', models.DecimalField(decimal_places=1, max_digits=4)),
                ('quality', models.CharField(choices=[('Poor', '😴 Poor'), ('Okay', '🙂 Okay'), ('Good', '😊 Good'), ('Great', '⭐ Great')], default='Okay', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
