# Generated by Django 5.2.8 on 2026-08-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_sleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep',
            name='sleep_type',
            field=models.CharField(choices=[('Sleep', '😴 Sleep'), ('Nap', '💤 Nap')], default='Sleep', max_length=10),
        ),
    ]
